### ISSUE TITLE
Adding characters to edge weights results in NaN

### ISSUE THREAD

**Issue by vitorvelozo** [JVitorCarv/simple-graphs#12]
![image](https://github.com/JVitorCarv/simple-graphs/assets/89556957/9c36b7f9-d365-456c-825c-ce5faa7522c9)
![image](https://github.com/JVitorCarv/simple-graphs/assets/89556957/32640bc8-b5a0-49b4-aef9-c52100ca1599)

**Comment by MatheusBarros23** [comment]
Fixed with [PR-14](https://github.com/JVitorCarv/simple-graphs/pull/14)

**Comment by MatheusBarros23** [comment]
Fixed with [PR-14](https://github.com/JVitorCarv/simple-graphs/pull/14)
